### ISSUE TITLE
Wall collision is broken

### ISSUE THREAD

**Issue by haykam821** [haykam821/Mootwo#1]
I can easily walk into the wall without any barriers.

![Walking into the wall](https://user-images.githubusercontent.com/24855774/27996393-1bd313f6-64af-11e7-8830-7fcdc2679f28.png)

Walking any further than this would teleport me to the center of the map, thanks to these lines:

```js
} else if (x < 0 || x > limit || y < 0 || y > limit) {
    x = 7200;
    y = 7200;
}
```

The river also pushes me out of map, and I'll keep going left until I manually move and get teleported to the map's center.

**Comment by Tokyo-tech** [comment]
Make me a script of it
